// Built-in fallback pool of free LeetCode problems, used only when the live
// problem-list query fails (LeetCode changes its GraphQL schema occasionally).
// Problem statements, examples and starter code are still fetched live.

export const FALLBACK_SLUGS = {
  Easy: [
    "two-sum", "palindrome-number", "roman-to-integer", "longest-common-prefix", "valid-parentheses",
    "merge-two-sorted-lists", "search-insert-position", "length-of-last-word", "plus-one", "add-binary",
    "sqrtx", "climbing-stairs", "remove-duplicates-from-sorted-list", "merge-sorted-array", "same-tree",
    "symmetric-tree", "maximum-depth-of-binary-tree", "balanced-binary-tree", "minimum-depth-of-binary-tree",
    "path-sum", "pascals-triangle", "pascals-triangle-ii", "best-time-to-buy-and-sell-stock", "valid-palindrome",
    "single-number", "reverse-linked-list", "contains-duplicate", "invert-binary-tree", "valid-anagram",
    "binary-search", "move-zeroes", "power-of-two", "missing-number", "counting-bits", "fizz-buzz",
    "majority-element", "happy-number", "reverse-string", "ransom-note", "first-unique-character-in-a-string",
    "intersection-of-two-arrays", "intersection-of-two-arrays-ii", "longest-palindrome", "fibonacci-number",
    "squares-of-a-sorted-array", "middle-of-the-linked-list", "backspace-string-compare", "height-checker",
    "relative-sort-array", "n-th-tribonacci-number", "running-sum-of-1d-array", "shuffle-the-array",
    "kids-with-the-greatest-number-of-candies", "richest-customer-wealth", "add-strings", "hamming-distance",
    "merge-two-binary-trees", "range-sum-of-bst", "diameter-of-binary-tree", "subtree-of-another-tree",
    "count-negative-numbers-in-a-sorted-matrix", "find-all-numbers-disappeared-in-an-array", "flipping-an-image",
    "transpose-matrix", "isomorphic-strings", "word-pattern", "can-place-flowers", "maximum-average-subarray-i",
    "find-pivot-index", "longest-continuous-increasing-subsequence", "degree-of-an-array", "to-lower-case",
    "jewels-and-stones", "unique-morse-code-words", "positions-of-large-groups", "binary-gap", "lemonade-change",
    "monotonic-array", "valid-mountain-array", "add-to-array-form-of-integer", "remove-all-adjacent-duplicates-in-string",
    "greatest-common-divisor-of-strings", "find-numbers-with-even-number-of-digits", "check-if-it-is-a-straight-line",
    "number-of-good-pairs", "matrix-diagonal-sum", "defanging-an-ip-address", "decompress-run-length-encoded-list",
    "build-array-from-permutation", "concatenation-of-array", "final-value-of-variable-after-performing-operations",
    "maximum-number-of-words-found-in-sentences", "count-of-matches-in-tournament", "check-if-the-sentence-is-pangram",
    "sum-of-all-subset-xor-totals", "find-the-highest-altitude", "reverse-words-in-a-string-iii", "merge-strings-alternately",
    "min-cost-climbing-stairs", "is-subsequence", "average-of-levels-in-binary-tree", "assign-cookies",
    "repeated-substring-pattern", "third-maximum-number", "arranging-coins", "find-the-difference", "island-perimeter",
    "max-consecutive-ones", "keyboard-row", "base-7", "relative-ranks", "perfect-number", "detect-capital",
    "longest-harmonious-subsequence", "set-mismatch", "maximum-product-of-three-numbers", "robot-return-to-origin",
    "image-smoother", "second-minimum-node-in-a-binary-tree", "baseball-game", "binary-number-with-alternating-bits",
    "count-binary-substrings", "search-in-a-binary-search-tree", "design-hashset", "design-hashmap",
    "largest-number-at-least-twice-of-others", "shortest-completing-word", "flood-fill", "min-cost-climbing-stairs",
    "rotate-string", "unique-email-addresses", "sort-array-by-parity", "leaf-similar-trees", "fair-candy-swap",
    "uncommon-words-from-two-sentences", "x-of-a-kind-in-a-deck-of-cards", "reverse-only-letters", "long-pressed-name",
    "univalued-binary-tree", "largest-perimeter-triangle", "sum-of-even-numbers-after-queries", "find-the-town-judge",
    "available-captures-for-rook", "find-common-characters", "maximize-sum-of-array-after-k-negations",
    "complement-of-base-10-integer", "partition-array-into-three-parts-with-equal-sum", "binary-prefix-divisible-by-5",
    "remove-outermost-parentheses", "sum-of-root-to-leaf-binary-numbers", "divisor-game", "last-stone-weight",
    "occurrences-after-bigram", "duplicate-zeros", "distribute-candies-to-people", "number-of-equivalent-domino-pairs",
    "distance-between-bus-stops", "day-of-the-week", "minimum-absolute-difference", "maximum-number-of-balloons",
    "minimum-cost-to-move-chips-to-the-same-position", "split-a-string-in-balanced-strings", "cells-with-odd-values-in-a-matrix",
    "shift-2d-grid", "minimum-time-visiting-all-points", "find-winner-on-a-tic-tac-toe-game",
    "subtract-the-product-and-sum-of-digits-of-an-integer", "element-appearing-more-than-25-in-sorted-array",
    "convert-binary-number-in-a-linked-list-to-integer", "replace-elements-with-greatest-element-on-right-side",
    "decrypt-string-from-alphabet-to-integer-mapping", "maximum-69-number", "how-many-numbers-are-smaller-than-the-current-number",
    "rank-transform-of-an-array", "sort-integers-by-the-number-of-1-bits", "number-of-steps-to-reduce-a-number-to-zero",
    "lucky-numbers-in-a-matrix", "find-lucky-integer-in-an-array", "count-largest-group", "string-matching-in-an-array",
    "minimum-value-to-get-positive-step-by-step-sum", "kids-with-the-greatest-number-of-candies", "number-of-students-doing-homework-at-a-given-time",
    "make-two-arrays-equal-by-reversing-subarrays", "average-salary-excluding-the-minimum-and-maximum-salary",
    "path-crossing", "can-make-arithmetic-progression-from-sequence", "xor-operation-in-an-array",
    "number-of-good-pairs", "water-bottles", "count-odd-numbers-in-an-interval-range", "kth-missing-positive-number",
    "three-consecutive-odds", "thousand-separator", "most-visited-sector-in-a-circular-track", "detect-pattern-of-length-m-repeated-k-or-more-times",
    "matrix-diagonal-sum", "replace-all-s-to-avoid-consecutive-repeating-characters", "special-positions-in-a-binary-matrix",
    "sum-of-all-odd-length-subarrays", "crawler-log-folder", "design-parking-system", "maximum-nesting-depth-of-the-parentheses",
    "mean-of-array-after-removing-some-elements", "largest-substring-between-two-equal-characters", "slowest-key",
    "sort-array-by-increasing-frequency", "check-array-formation-through-concatenation", "get-maximum-in-generated-array",
    "defuse-the-bomb", "design-an-ordered-stream", "richest-customer-wealth", "goal-parser-interpretation",
    "count-the-number-of-consistent-strings", "count-good-triplets", "merge-in-between-linked-lists",
    "calculate-money-in-leetcode-bank", "decode-xored-array", "number-of-rectangles-that-can-form-the-largest-square",
    "latest-time-by-replacing-hidden-digits", "maximum-number-of-balls-in-a-box", "sum-of-unique-elements",
    "minimum-changes-to-make-alternating-binary-string", "longest-nice-substring", "merge-strings-alternately",
    "count-items-matching-a-rule", "find-center-of-star-graph", "second-largest-digit-in-a-string", "maximum-ascending-subarray-sum",
    "number-of-different-integers-in-a-string", "truncate-sentence", "sign-of-the-product-of-an-array",
    "minimum-operations-to-make-the-array-increasing", "check-if-the-sentence-is-pangram", "replace-all-digits-with-characters",
    "sum-of-digits-in-base-k", "sorting-the-sentence", "maximum-population-year", "longer-contiguous-segments-of-ones-than-zeros",
    "substrings-of-size-three-with-distinct-characters", "determine-whether-matrix-can-be-obtained-by-rotation",
    "check-if-all-the-integers-in-a-range-are-covered", "redistribute-characters-to-make-all-strings-equal",
    "largest-odd-number-in-string", "remove-one-element-to-make-the-array-strictly-increasing", "maximum-product-difference-between-two-pairs",
    "count-square-sum-triples", "build-array-from-permutation", "concatenation-of-array", "maximum-number-of-words-you-can-type",
    "check-if-string-is-a-prefix-of-array", "minimum-time-to-type-word-using-special-typewriter", "find-greatest-common-divisor-of-array",
    "number-of-strings-that-appear-as-substrings-in-word", "minimum-difference-between-highest-and-lowest-of-k-scores",
    "find-the-middle-index-in-array", "count-special-quadruplets", "reverse-prefix-of-word", "maximum-difference-between-increasing-elements",
    "convert-1d-array-into-2d-array", "final-value-of-variable-after-performing-operations", "two-furthest-houses-with-different-colors",
    "count-vowel-substrings-of-a-string", "check-whether-two-strings-are-almost-equivalent", "find-first-palindromic-string-in-the-array",
    "a-number-after-a-double-reversal", "capitalize-the-title", "divide-a-string-into-groups-of-size-k", "minimum-sum-of-four-digit-number-after-splitting-digits",
    "sort-even-and-odd-indices-independently", "count-operations-to-obtain-zero", "counting-words-with-a-given-prefix",
    "most-frequent-number-following-key-in-an-array", "cells-in-a-range-on-an-excel-sheet", "find-the-difference-of-two-arrays",
    "minimum-bit-flips-to-convert-number", "largest-3-same-digit-number-in-string", "count-prefixes-of-a-given-string",
    "find-closest-number-to-zero", "calculate-digit-sum-of-a-string", "percentage-of-letter-in-string", "min-max-game",
    "strong-password-checker-ii", "calculate-amount-paid-in-taxes", "greatest-english-letter-in-upper-and-lower-case",
    "count-asterisks", "decode-the-message", "minimum-amount-of-time-to-fill-cups", "first-letter-to-appear-twice",
    "make-array-zero-by-subtracting-equal-amounts", "maximum-number-of-pairs-in-array", "best-poker-hand",
    "merge-similar-items", "minimum-recolors-to-get-k-consecutive-black-blocks", "largest-local-values-in-a-matrix",
    "minimum-hours-of-training-to-win-a-competition", "longest-subsequence-with-limited-sum", "find-subarrays-with-equal-sum",
    "smallest-even-multiple", "count-days-spent-together", "number-of-common-factors", "the-employee-that-worked-on-the-longest-task",
    "number-of-valid-clock-times", "odd-string-difference", "average-value-of-even-numbers-that-are-divisible-by-three",
    "convert-the-temperature", "number-of-unequal-triplets-in-array", "minimum-cuts-to-divide-a-circle", "circular-sentence",
    "delete-greatest-value-in-each-row", "maximum-value-of-a-string-in-an-array", "count-pairs-of-similar-strings",
    "shortest-distance-to-target-string-in-a-circular-array", "difference-between-element-sum-and-digit-sum-of-an-array",
    "alternating-digit-sum", "maximum-count-of-positive-integer-and-negative-integer", "find-the-array-concatenation-value",
    "left-and-right-sum-differences", "merge-two-2d-arrays-by-summing-values", "pass-the-pillow", "k-items-with-the-maximum-sum",
    "form-smallest-number-from-two-digit-arrays", "find-the-distinct-difference-array", "buy-two-chocolates",
    "neither-minimum-nor-maximum", "find-the-losers-of-the-circular-game", "minimum-string-length-after-removing-substrings",
    "semi-ordered-permutation", "sum-of-squares-of-special-elements", "check-if-array-is-good", "faulty-keyboard",
    "number-of-employees-who-met-the-target", "account-balance-after-rounded-purchase", "max-pair-sum-in-an-array",
    "furthest-point-from-origin", "minimum-absolute-difference-between-elements-with-constraint", "minimum-right-shifts-to-sort-the-array",
  ],
  Medium: [
    "add-two-numbers", "longest-substring-without-repeating-characters", "zigzag-conversion", "reverse-integer",
    "string-to-integer-atoi", "container-with-most-water", "integer-to-roman", "3sum", "3sum-closest",
    "letter-combinations-of-a-phone-number", "4sum", "remove-nth-node-from-end-of-list", "generate-parentheses",
    "swap-nodes-in-pairs", "divide-two-integers", "next-permutation", "search-in-rotated-sorted-array",
    "find-first-and-last-position-of-element-in-sorted-array", "valid-sudoku", "combination-sum", "combination-sum-ii",
    "permutations", "permutations-ii", "rotate-image", "group-anagrams", "powx-n", "maximum-subarray", "spiral-matrix",
    "jump-game", "merge-intervals", "insert-interval", "spiral-matrix-ii", "rotate-list", "unique-paths", "unique-paths-ii",
    "minimum-path-sum", "simplify-path", "set-matrix-zeroes", "search-a-2d-matrix", "sort-colors", "combinations",
    "subsets", "word-search", "remove-duplicates-from-sorted-list-ii", "partition-list", "subsets-ii", "decode-ways",
    "reverse-linked-list-ii", "restore-ip-addresses", "unique-binary-search-trees", "validate-binary-search-tree",
    "binary-tree-level-order-traversal", "binary-tree-zigzag-level-order-traversal",
    "construct-binary-tree-from-preorder-and-inorder-traversal", "construct-binary-tree-from-inorder-and-postorder-traversal",
    "binary-tree-level-order-traversal-ii", "path-sum-ii", "triangle", "best-time-to-buy-and-sell-stock-ii",
    "longest-consecutive-sequence", "sum-root-to-leaf-numbers", "palindrome-partitioning", "gas-station", "single-number-ii",
    "word-break", "lru-cache", "insertion-sort-list", "sort-list", "evaluate-reverse-polish-notation",
    "reverse-words-in-a-string", "maximum-product-subarray", "find-minimum-in-rotated-sorted-array", "min-stack",
    "compare-version-numbers", "fraction-to-recurring-decimal", "two-sum-ii-input-array-is-sorted", "majority-element-ii",
    "factorial-trailing-zeroes", "binary-search-tree-iterator", "largest-number", "rotate-array", "house-robber",
    "binary-tree-right-side-view", "number-of-islands", "bitwise-and-of-numbers-range", "count-primes", "course-schedule",
    "implement-trie-prefix-tree", "minimum-size-subarray-sum", "design-add-and-search-words-data-structure", "house-robber-ii",
    "kth-largest-element-in-an-array", "combination-sum-iii", "maximal-square", "count-complete-tree-nodes", "rectangle-area",
    "basic-calculator-ii", "kth-smallest-element-in-a-bst", "lowest-common-ancestor-of-a-binary-tree", "product-of-array-except-self",
    "search-a-2d-matrix-ii", "different-ways-to-add-parentheses", "single-number-iii", "ugly-number-ii", "h-index",
    "perfect-squares", "find-the-duplicate-number", "game-of-life", "bulls-and-cows", "longest-increasing-subsequence",
    "range-sum-query-2d-immutable", "additive-number", "minimum-height-trees", "super-ugly-number", "remove-duplicate-letters",
    "maximum-product-of-word-lengths", "bulb-switcher", "coin-change", "odd-even-linked-list", "verify-preorder-serialization-of-a-binary-tree",
    "increasing-triplet-subsequence", "integer-break", "top-k-frequent-elements", "wiggle-subsequence", "combination-sum-iv",
    "kth-smallest-element-in-a-sorted-matrix", "lexicographical-numbers", "longest-absolute-file-path", "elimination-game",
    "utf-8-validation", "decode-string", "longest-substring-with-at-least-k-repeating-characters", "rotate-function",
    "integer-replacement", "evaluate-division", "remove-k-digits", "queue-reconstruction-by-height", "arithmetic-slices",
    "partition-equal-subset-sum", "pacific-atlantic-water-flow", "battleships-in-a-board", "maximum-xor-of-two-numbers-in-an-array",
    "longest-repeating-character-replacement", "minimum-genetic-mutation", "non-overlapping-intervals", "find-right-interval",
    "path-sum-iii", "find-all-anagrams-in-a-string", "find-all-duplicates-in-an-array", "add-two-numbers-ii",
    "minimum-number-of-arrows-to-burst-balloons", "minimum-moves-to-equal-array-elements", "4sum-ii", "132-pattern",
    "circular-array-loop", "minimum-moves-to-equal-array-elements-ii", "can-i-win", "unique-substrings-in-wraparound-string",
    "validate-ip-address", "matchsticks-to-square", "ones-and-zeroes", "heaters", "total-hamming-distance", "magical-string",
    "predict-the-winner", "increasing-subsequences", "target-sum", "diagonal-traverse", "next-greater-element-ii",
    "most-frequent-subtree-sum", "find-bottom-left-tree-value", "find-largest-value-in-each-tree-row", "longest-palindromic-subsequence",
    "coin-change-ii", "longest-uncommon-subsequence-ii", "continuous-subarray-sum", "longest-word-in-dictionary-through-deleting",
    "contiguous-array", "beautiful-arrangement", "minesweeper", "k-diff-pairs-in-an-array", "complex-number-multiplication",
    "01-matrix", "number-of-provinces", "optimal-division", "next-greater-element-iii", "subarray-sum-equals-k", "array-nesting",
    "permutation-in-string", "out-of-boundary-paths", "shortest-unsorted-continuous-subarray", "delete-operation-for-two-strings",
    "fraction-addition-and-subtraction", "valid-square", "find-duplicate-file-in-system", "valid-triangle-number", "add-bold-tag-in-string",
    "task-scheduler", "add-one-row-to-tree", "design-circular-deque", "sum-of-square-numbers", "exclusive-time-of-functions",
    "shopping-offers", "solve-the-equation", "design-circular-queue", "maximum-length-of-pair-chain", "palindromic-substrings",
    "replace-words", "dota2-senate", "2-keys-keyboard", "find-duplicate-subtrees", "maximum-binary-tree", "find-k-closest-elements",
    "split-array-into-consecutive-subsequences", "maximum-width-of-binary-tree", "non-decreasing-array", "trim-a-binary-search-tree",
    "maximum-swap", "bulb-switcher-ii", "number-of-longest-increasing-subsequence", "implement-magic-dictionary", "map-sum-pairs",
    "valid-parenthesis-string", "next-closest-time", "redundant-connection", "repeated-string-match", "longest-univalue-path",
    "knight-probability-in-chessboard", "top-k-frequent-words", "max-area-of-island", "partition-to-k-equal-sum-subsets",
    "kth-largest-element-in-a-stream", "design-linked-list", "minimum-ascii-delete-sum-for-two-strings", "subarray-product-less-than-k",
    "best-time-to-buy-and-sell-stock-with-transaction-fee", "maximum-length-of-repeated-subarray", "accounts-merge", "remove-comments",
    "split-linked-list-in-parts", "my-calendar-i", "my-calendar-ii", "asteroid-collision", "monotone-increasing-digits",
    "daily-temperatures", "delete-and-earn", "network-delay-time", "prefix-and-suffix-search", "open-the-lock", "reach-a-number",
    "pyramid-transition-matrix", "global-and-local-inversions", "swap-adjacent-in-lr-string", "k-th-symbol-in-grammar",
    "rabbits-in-forest", "letter-case-permutation", "is-graph-bipartite", "cheapest-flights-within-k-stops", "rotated-digits",
    "escape-the-ghosts", "domino-and-tromino-tiling", "number-of-matching-subsequences", "valid-tic-tac-toe-state",
    "number-of-subarrays-with-bounded-maximum", "all-paths-from-source-to-target", "champagne-tower", "find-eventual-safe-states",
    "max-increase-to-keep-city-skyline", "soup-servings", "expressive-words", "subdomain-visit-count", "largest-sum-of-averages",
    "binary-tree-pruning", "ambiguous-coordinates", "linked-list-components", "most-common-word", "short-encoding-of-words",
    "card-flipping-game", "binary-trees-with-factors", "friends-of-appropriate-ages", "most-profit-assigning-work",
    "masking-personal-information", "find-and-replace-in-string", "image-overlap", "new-21-game", "push-dominoes",
    "longest-mountain-in-array", "hand-of-straights", "shifting-letters", "maximize-distance-to-closest-person", "loud-and-rich",
    "peak-index-in-a-mountain-array", "car-fleet", "exam-room", "score-of-parentheses", "mirror-reflection", "score-after-flipping-matrix",
    "all-nodes-distance-k-in-binary-tree", "smallest-subtree-with-all-the-deepest-nodes", "prime-palindrome", "reordered-power-of-2",
    "advantage-shuffle", "length-of-longest-fibonacci-subsequence", "walking-robot-simulation", "koko-eating-bananas", "stone-game",
    "decoded-string-at-index", "boats-to-save-people", "spiral-matrix-iii", "possible-bipartition", "find-and-replace-pattern",
    "all-possible-full-binary-trees", "bitwise-ors-of-subarrays", "fruit-into-baskets", "sum-of-subarray-minimums",
    "snakes-and-ladders", "smallest-range-ii", "online-election", "sort-an-array", "partition-array-into-disjoint-intervals",
    "word-subsets", "maximum-sum-circular-subarray", "complete-binary-tree-inserter", "minimum-add-to-make-parentheses-valid",
    "3sum-with-multiplicity", "flip-string-to-monotone-increasing", "binary-subarrays-with-sum", "minimum-falling-path-sum",
    "shortest-bridge", "knight-dialer", "reorder-data-in-log-files", "minimum-area-rectangle", "minimum-increment-to-make-array-unique",
    "validate-stack-sequences", "most-stones-removed-with-same-row-or-column", "bag-of-tokens", "largest-time-for-given-digits",
    "reveal-cards-in-increasing-order", "flip-equivalent-binary-trees", "array-of-doubled-pairs", "delete-columns-to-make-sorted-ii",
    "prison-cells-after-n-days", "check-completeness-of-a-binary-tree", "regions-cut-by-slashes", "maximum-width-ramp",
    "vowel-spellchecker", "numbers-with-same-consecutive-differences", "flip-binary-tree-to-match-preorder-traversal",
    "pancake-sorting", "powerful-integers", "k-closest-points-to-origin", "subarray-sums-divisible-by-k", "longest-turbulent-subarray",
    "distribute-coins-in-binary-tree", "time-based-key-value-store", "minimum-cost-for-tickets", "interval-list-intersections",
    "smallest-string-starting-from-leaf", "satisfiability-of-equality-equations", "broken-calculator", "rotting-oranges",
    "maximum-binary-tree-ii", "check-if-word-is-valid-after-substitutions", "max-consecutive-ones-iii", "clumsy-factorial",
    "minimum-domino-rotations-for-equal-row", "construct-binary-search-tree-from-preorder-traversal",
    "pairs-of-songs-with-total-durations-divisible-by-60", "capacity-to-ship-packages-within-d-days", "best-sightseeing-pair",
    "smallest-integer-divisible-by-k", "binary-string-with-substrings-representing-1-to-n", "convert-to-base-2",
    "next-greater-node-in-linked-list", "number-of-enclaves", "camelcase-matching", "video-stitching",
    "maximum-difference-between-node-and-ancestor", "longest-arithmetic-subsequence", "two-city-scheduling",
    "maximum-sum-of-two-non-overlapping-subarrays", "coloring-a-border", "uncrossed-lines", "binary-search-tree-to-greater-sum-tree",
    "minimum-score-triangulation-of-polygon", "robot-bounded-in-circle", "partition-array-for-maximum-sum", "longest-string-chain",
    "last-stone-weight-ii", "grumpy-bookstore-owner", "previous-permutation-with-one-swap", "flip-columns-for-maximum-number-of-equal-rows",
    "adding-two-negabinary-numbers", "letter-tile-possibilities", "insufficient-nodes-in-root-to-leaf-paths", "smallest-subsequence-of-distinct-characters",
    "largest-values-from-labels", "shortest-path-in-binary-matrix", "statistics-from-a-large-sample", "car-pooling",
    "path-in-zigzag-labelled-binary-tree", "filling-bookcase-shelves", "corporate-flight-bookings", "delete-nodes-and-return-forest",
    "lowest-common-ancestor-of-deepest-leaves", "longest-well-performing-interval", "shortest-path-with-alternating-colors",
    "minimum-cost-tree-from-leaf-values", "alphabet-board-path", "largest-1-bordered-square", "stone-game-ii", "longest-common-subsequence",
    "decrease-elements-to-make-array-zigzag", "binary-tree-coloring-game", "snapshot-array", "number-of-dice-rolls-with-target-sum",
    "swap-for-longest-repeated-character-substring", "can-make-palindrome-from-substring", "maximum-subarray-sum-with-one-deletion",
    "invalid-transactions", "compare-strings-by-frequency-of-the-smallest-character", "ugly-number-iii", "smallest-string-with-swaps",
    "reverse-substrings-between-each-pair-of-parentheses", "k-concatenation-maximum-sum", "longest-arithmetic-subsequence-of-given-difference",
    "path-with-maximum-gold", "queens-that-can-attack-the-king", "remove-sub-folders-from-the-filesystem", "replace-the-substring-for-balanced-string",
    "number-of-closed-islands", "find-elements-in-a-contaminated-binary-tree", "greatest-sum-divisible-by-three", "count-servers-that-communicate",
    "search-suggestions-system", "count-square-submatrices-with-all-ones", "find-the-smallest-divisor-given-a-threshold",
    "remove-covered-intervals", "sequential-digits", "maximum-side-length-of-a-square-with-sum-less-than-or-equal-to-threshold",
    "divide-array-in-sets-of-k-consecutive-numbers", "maximum-number-of-occurrences-of-a-substring", "sum-of-mutated-array-closest-to-target",
    "deepest-leaves-sum", "all-elements-in-two-binary-search-trees", "jump-game-iii", "xor-queries-of-a-subarray",
    "get-watched-videos-by-your-friends", "minimum-number-of-steps-to-make-two-strings-anagram", "maximum-number-of-events-that-can-be-attended",
    "number-of-operations-to-make-network-connected", "minimum-difficulty-of-a-job-schedule", "angle-between-hands-of-a-clock",
    "jump-game-iv", "break-a-palindrome", "sort-the-matrix-diagonally", "reduce-array-size-to-the-half", "maximum-product-of-splitted-binary-tree",
    "jump-game-v", "filter-restaurants-by-vegan-friendly-price-and-distance", "find-the-city-with-the-smallest-number-of-neighbors-at-a-threshold-distance",
    "number-of-substrings-containing-all-three-characters", "count-all-valid-pickup-and-delivery-options", "maximum-students-taking-exam",
    "tweet-counts-per-frequency", "maximum-number-of-events-that-can-be-attended", "validate-binary-tree-nodes", "closest-divisors",
    "largest-multiple-of-three", "count-negative-numbers-in-a-sorted-matrix", "product-of-the-last-k-numbers", "maximum-number-of-events-that-can-be-attended",
    "bulb-switcher-iii", "maximum-sum-bst-in-binary-tree", "design-underground-system", "find-all-good-strings",
    "longest-happy-string", "stone-game-iii", "string-matching-in-an-array", "queries-on-a-permutation-with-key", "html-entity-parser",
    "number-of-ways-to-paint-n-3-grid", "minimum-subsequence-in-non-increasing-order", "number-of-steps-to-reduce-a-number-in-binary-representation-to-one",
    "longest-happy-prefix", "find-the-kth-smallest-sum-of-a-matrix-with-sorted-rows", "build-an-array-with-stack-operations",
    "count-triplets-that-can-form-two-arrays-of-equal-xor", "minimum-time-to-collect-all-apples-in-a-tree", "number-of-ways-of-cutting-a-pizza",
    "check-if-a-string-can-break-another-string", "number-of-ways-to-wear-different-hats-to-each-other", "destination-city",
    "check-if-all-1s-are-at-least-length-k-places-away", "longest-continuous-subarray-with-absolute-diff-less-than-or-equal-to-limit",
    "find-the-minimum-number-of-fibonacci-numbers-whose-sum-is-k", "the-k-th-lexicographical-string-of-all-happy-strings-of-length-n",
    "restore-the-array", "maximum-points-you-can-obtain-from-cards", "diagonal-traverse-ii", "constrained-subsequence-sum",
    "kids-with-the-greatest-number-of-candies", "max-difference-you-can-get-from-changing-an-integer", "check-if-a-string-can-break-another-string",
    "rearrange-words-in-a-sentence", "people-whose-list-of-favorite-companies-is-not-a-subset-of-another-list",
    "maximum-number-of-darts-inside-of-a-circular-dartboard", "check-if-a-word-occurs-as-a-prefix-of-any-word-in-a-sentence",
    "maximum-number-of-vowels-in-a-substring-of-given-length", "pseudo-palindromic-paths-in-a-binary-tree",
    "max-dot-product-of-two-subsequences", "make-two-arrays-equal-by-reversing-subarrays", "check-if-a-string-contains-all-binary-codes-of-size-k",
    "course-schedule-iv", "cherry-pickup-ii", "maximum-product-of-two-elements-in-an-array", "maximum-area-of-a-piece-of-cake-after-horizontal-and-vertical-cuts",
    "reorder-routes-to-make-all-paths-lead-to-the-city-zero", "probability-of-a-two-boxes-having-the-same-number-of-distinct-balls",
    "shuffle-the-array", "the-k-strongest-values-in-an-array", "design-browser-history", "paint-house-iii", "final-prices-with-a-special-discount-in-a-shop",
    "subrectangle-queries", "find-two-non-overlapping-sub-arrays-each-with-target-sum", "allocate-mailboxes", "running-sum-of-1d-array",
    "least-number-of-unique-integers-after-k-removals", "minimum-number-of-days-to-make-m-bouquets", "kth-ancestor-of-a-tree-node",
    "xor-operation-in-an-array", "making-file-names-unique", "avoid-flood-in-the-city", "find-critical-and-pseudo-critical-edges-in-minimum-spanning-tree",
    "average-salary-excluding-the-minimum-and-maximum-salary", "the-kth-factor-of-n", "longest-subarray-of-1s-after-deleting-one-element",
    "parallel-courses-ii", "path-crossing", "check-if-array-pairs-are-divisible-by-k", "number-of-subsequences-that-satisfy-the-given-sum-condition",
    "max-value-of-equation", "can-make-arithmetic-progression-from-sequence", "last-moment-before-all-ants-fall-out-of-a-plank",
    "count-submatrices-with-all-ones", "minimum-possible-integer-after-at-most-k-adjacent-swaps-on-digits", "number-of-good-pairs",
    "number-of-substrings-with-only-1s", "path-with-maximum-probability", "best-position-for-a-service-centre", "water-bottles",
    "number-of-nodes-in-the-sub-tree-with-the-same-label", "maximum-number-of-non-overlapping-substrings", "find-a-value-of-a-mysterious-function-closest-to-target",
    "count-odd-numbers-in-an-interval-range", "number-of-sub-arrays-with-odd-sum", "number-of-good-ways-to-split-a-string",
    "minimum-number-of-increments-on-subarrays-to-form-a-target-array", "kth-missing-positive-number", "can-convert-string-in-k-moves",
    "minimum-insertions-to-balance-a-parentheses-string", "find-longest-awesome-substring", "three-consecutive-odds",
    "minimum-operations-to-make-array-equal", "magnetic-force-between-two-balls", "minimum-number-of-days-to-eat-n-oranges",
    "thousand-separator", "minimum-number-of-vertices-to-reach-all-nodes", "minimum-numbers-of-function-calls-to-make-target-array",
    "detect-cycles-in-2d-grid", "most-visited-sector-in-a-circular-track", "maximum-number-of-coins-you-can-get",
    "find-latest-group-of-size-m", "stone-game-v", "detect-pattern-of-length-m-repeated-k-or-more-times",
    "maximum-length-of-subarray-with-positive-product", "minimum-number-of-days-to-disconnect-island",
    "number-of-ways-to-reorder-array-to-get-same-bst", "matrix-diagonal-sum", "number-of-ways-to-split-a-string",
    "shortest-subarray-to-be-removed-to-make-array-sorted", "count-all-possible-routes", "replace-all-s-to-avoid-consecutive-repeating-characters",
    "number-of-ways-where-square-of-number-is-equal-to-product-of-two-numbers", "minimum-deletion-cost-to-avoid-repeating-letters",
    "remove-max-number-of-edges-to-keep-graph-fully-traversable", "special-positions-in-a-binary-matrix", "count-unhappy-friends",
    "min-cost-to-connect-all-points", "check-if-string-is-transformable-with-substring-sort-operations", "sum-of-all-odd-length-subarrays",
    "maximum-sum-obtained-of-any-permutation", "make-sum-divisible-by-p", "rearrange-spaces-between-words",
    "split-a-string-into-the-max-number-of-unique-substrings", "maximum-non-negative-product-in-a-matrix",
    "minimum-cost-to-connect-two-groups-of-points", "crawler-log-folder", "maximum-profit-of-operating-a-centennial-wheel",
    "throne-inheritance", "maximum-number-of-achievable-transfer-requests", "design-parking-system", "alert-using-same-key-card-three-or-more-times-in-a-one-hour-period",
    "find-valid-matrix-given-row-and-column-sums", "find-servers-that-handled-most-number-of-requests",
    "maximum-nesting-depth-of-the-parentheses", "maximal-network-rank", "split-two-strings-to-make-palindrome", "count-subtrees-with-max-distance-between-cities",
    "mean-of-array-after-removing-some-elements", "coordinate-with-maximum-network-quality", "number-of-sets-of-k-non-overlapping-line-segments",
    "fancy-sequence", "largest-substring-between-two-equal-characters", "lexicographically-smallest-string-after-applying-operations",
    "best-team-with-no-conflicts", "graph-connectivity-with-threshold", "slowest-key", "arithmetic-subarrays",
    "path-with-minimum-effort", "rank-transform-of-a-matrix", "sort-array-by-increasing-frequency", "widest-vertical-area-between-two-points-containing-no-points",
    "count-substrings-that-differ-by-one-character", "number-of-ways-to-form-a-target-string-given-a-dictionary", "check-array-formation-through-concatenation",
    "count-sorted-vowel-strings", "furthest-building-you-can-reach", "kth-smallest-instructions", "get-maximum-in-generated-array",
    "minimum-deletions-to-make-character-frequencies-unique", "sell-diminishing-valued-colored-balls", "create-sorted-array-through-instructions",
    "defuse-the-bomb", "minimum-deletions-to-make-string-balanced", "minimum-jumps-to-reach-home", "distribute-repeating-integers",
    "design-an-ordered-stream", "determine-if-two-strings-are-close", "minimum-operations-to-reduce-x-to-zero", "maximize-grid-happiness",
    "richest-customer-wealth", "find-the-most-competitive-subsequence", "minimum-moves-to-make-array-complementary",
    "minimize-deviation-in-array", "goal-parser-interpretation", "max-number-of-k-sum-pairs", "concatenation-of-consecutive-binary-numbers",
    "minimum-incompatibility", "count-the-number-of-consistent-strings", "sum-of-absolute-differences-in-a-sorted-array",
    "minimum-number-of-removals-to-make-mountain-array", "ways-to-make-a-fair-array", "minimum-initial-energy-to-finish-tasks",
  ],
  Hard: [
    "median-of-two-sorted-arrays", "regular-expression-matching", "merge-k-sorted-lists", "reverse-nodes-in-k-group",
    "substring-with-concatenation-of-all-words", "longest-valid-parentheses", "sudoku-solver", "first-missing-positive",
    "trapping-rain-water", "wildcard-matching", "n-queens", "n-queens-ii", "text-justification", "edit-distance",
    "minimum-window-substring", "largest-rectangle-in-histogram", "maximal-rectangle", "scramble-string", "distinct-subsequences",
    "binary-tree-maximum-path-sum", "word-ladder", "word-ladder-ii", "candy", "word-break-ii", "max-points-on-a-line",
    "lfu-cache", "the-skyline-problem", "sliding-window-maximum", "basic-calculator", "shortest-palindrome", "word-search-ii",
    "contains-duplicate-iii", "find-median-from-data-stream", "best-time-to-buy-and-sell-stock-iv", "burst-balloons",
    "count-of-smaller-numbers-after-self", "remove-invalid-parentheses", "longest-increasing-path-in-a-matrix",
    "russian-doll-envelopes", "frog-jump", "split-array-largest-sum", "trapping-rain-water-ii", "minimum-number-of-refueling-stops",
    "swim-in-rising-water", "super-egg-drop", "shortest-subarray-with-sum-at-least-k", "k-similar-strings", "bus-routes",
    "couples-holding-hands", "cherry-pickup", "number-of-atoms", "longest-duplicate-substring",
    "smallest-range-covering-elements-from-k-lists", "critical-connections-in-a-network", "palindrome-pairs",
    "concatenated-words", "student-attendance-record-ii", "strange-printer", "k-inverse-pairs-array", "tallest-billboard",
    "poor-pigs", "reaching-points", "maximum-frequency-stack", "count-different-palindromic-subsequences",
    "parsing-a-boolean-expression", "minimum-insertion-steps-to-make-a-string-palindrome", "maximum-score-words-formed-by-letters",
    "jump-game-iv", "stone-game-iii", "constrained-subsequence-sum", "number-of-ways-of-cutting-a-pizza",
    "max-sum-of-rectangle-no-larger-than-k", "minimum-difficulty-of-a-job-schedule", "count-all-valid-pickup-and-delivery-options",
    "paint-house-iii", "stone-game-iv", "distinct-echo-substrings", "profitable-schemes", "maximum-performance-of-a-team",
    "minimum-number-of-days-to-eat-n-oranges", "minimum-cost-to-cut-a-stick", "count-subtrees-with-max-distance-between-cities",
    "find-k-th-smallest-pair-distance", "number-of-music-playlists", "sum-of-distances-in-tree", "shortest-path-visiting-all-nodes",
    "race-car", "super-palindromes", "orderly-queue", "valid-permutations-for-di-sequence", "three-equal-parts",
    "minimize-malware-spread", "numbers-at-most-n-given-digit-set", "least-operators-to-express-number", "binary-tree-cameras",
    "equal-rational-numbers", "odd-even-jump", "unique-paths-iii", "subarrays-with-k-different-integers",
    "minimum-number-of-k-consecutive-bit-flips", "number-of-squareful-arrays", "grid-illumination", "numbers-with-repeated-digits",
    "recover-a-tree-from-preorder-traversal", "escape-a-large-maze", "number-of-submatrices-that-sum-to-target", "brace-expansion-ii",
    "smallest-sufficient-team", "longest-chunked-palindrome-decomposition", "make-array-strictly-increasing", "dinner-plate-stacks",
    "sort-items-by-groups-respecting-dependencies", "count-vowels-permutation", "dice-roll-simulation", "maximum-equal-frequency",
    "handshakes-that-dont-cross", "palindrome-partitioning-iii", "minimum-number-of-flips-to-convert-binary-matrix-to-zero-matrix",
    "minimum-falling-path-sum-ii", "shortest-path-in-a-grid-with-obstacles-elimination", "maximum-candies-you-can-get-from-boxes",
    "number-of-paths-with-max-score", "verbal-arithmetic-puzzle", "minimum-insertion-steps-to-make-a-string-palindrome",
    "maximum-students-taking-exam", "largest-multiple-of-three", "find-all-good-strings", "longest-happy-prefix",
    "find-the-kth-smallest-sum-of-a-matrix-with-sorted-rows", "number-of-ways-to-wear-different-hats-to-each-other",
    "number-of-ways-of-cutting-a-pizza", "kth-ancestor-of-a-tree-node", "allocate-mailboxes", "find-critical-and-pseudo-critical-edges-in-minimum-spanning-tree",
    "parallel-courses-ii", "max-value-of-equation", "minimum-possible-integer-after-at-most-k-adjacent-swaps-on-digits",
    "best-position-for-a-service-centre", "find-a-value-of-a-mysterious-function-closest-to-target",
    "minimum-number-of-increments-on-subarrays-to-form-a-target-array", "find-longest-awesome-substring",
    "minimum-number-of-days-to-disconnect-island", "count-all-possible-routes", "remove-max-number-of-edges-to-keep-graph-fully-traversable",
    "check-if-string-is-transformable-with-substring-sort-operations", "maximum-sum-obtained-of-any-permutation",
    "minimum-cost-to-connect-two-groups-of-points", "maximum-number-of-achievable-transfer-requests", "find-servers-that-handled-most-number-of-requests",
    "number-of-sets-of-k-non-overlapping-line-segments", "fancy-sequence", "graph-connectivity-with-threshold",
    "rank-transform-of-a-matrix", "number-of-ways-to-form-a-target-string-given-a-dictionary", "kth-smallest-instructions",
    "sell-diminishing-valued-colored-balls", "create-sorted-array-through-instructions", "distribute-repeating-integers",
    "maximize-grid-happiness", "minimize-deviation-in-array", "minimum-incompatibility", "ways-to-make-a-fair-array",
    "minimum-initial-energy-to-finish-tasks",
  ],
};
